//* Imprimir los primeros 10 números en incrementos de 3 positivos
// Comenzamos desde 1 ya que queremos empezar con el número 1.
// El bucle continuará mientras el número actual (i) sea menor o igual a 10.
// En cada iteración, incrementamos i en 3 para que imprima números en incrementos de 3.
for (let i = 1; i <= 10; i += 3) {
    console.log(i); // Imprime el número actual en la consola.
}

//* Imprimir los primeros 10 números en decrementos de 3 (negativos)
// Comenzamos desde 1 ya que queremos empezar con el número 1.
// El bucle continuará mientras el número actual (i) sea mayor o igual a -10.
// En cada iteración, decrementamos i en 3 para que imprima números en decrementos de 3.
for (let i = 1; i >= -10; i -= 3) {
    console.log(i); // Imprime el número actual en la consola.
}
